language: python
python:
  - "2.7"

before_install:
- sudo apt-get -qq update

# command to install dependencies
install:

# command to run tests
script: for mod in caom2visitor; do cd $mod; virtualenv venv; source venv/bin/activate; pip install -r dev_requirements.txt; py.test --cov=$mod || break -1; deactivate; cd ..; done
