#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#***********************************************************************
#******************  CANADIAN ASTRONOMY DATA CENTRE  *******************
#*************  CENTRE CANADIEN DE DONNÉES ASTRONOMIQUES  **************
#                                                                                                                                                          
#  (c) 2010.                            (c) 2010.                                                                                                          
#  Government of Canada                 Gouvernement du Canada                                                                                             
#  National Research Council            Conseil national de recherches                                                                                     
#  Ottawa, Canada, K1A 0R6              Ottawa, Canada, K1A 0R6                                                                                            
#  All rights reserved                  Tous droits réservés                                                                                               
#                                                                                                                                                          
#  NRC disclaims any warranties,        Le CNRC dénie toute garantie                                                                                       
#  expressed, implied, or               énoncée, implicite ou légale,                                                                                      
#  statutory, of any kind with          de quelque nature que ce                                                                                           
#  respect to the software,             soit, concernant le logiciel,                                                                                      
#  including without limitation         y compris sans restriction                                                                                         
#  any warranty of merchantability      toute garantie de valeur                                                                                           
#  or fitness for a particular          marchande ou de pertinence                                                                                         
#  purpose. NRC shall not be            pour un usage particulier.                                                                                         
#  liable in any event for any          Le CNRC ne pourra en aucun cas                                                                                     
#  damages, whether direct or           être tenu responsable de tout                                                                                      
#  indirect, special or general,        dommage, direct ou indirect,                                                                                       
#  consequential or incidental,         particulier ou général,                                                                                            
#  arising from the use of the          accessoire ou fortuit, résultant                                                                                   
#  software.  Neither the name          de l'utilisation du logiciel. Ni                                                                                   
#  of the National Research             le nom du Conseil National de                                                                                      
#  Council of Canada nor the            Recherches du Canada ni les noms                                                                                   
#  names of its contributors may        de ses  participants ne peuvent                                                                                    
#  be used to endorse or promote        être utilisés pour approuver ou                                                                                    
#  products derived from this           promouvoir les produits dérivés                                                                                    
#  software without specific prior      de ce logiciel sans autorisation                                                                                   
#  written permission.                  préalable et particulière                                                                                          
#                                       par écrit.                                                                                                         
#                                                                                                                                                          
#  This file is part of the             Ce fichier fait partie du projet                                                                                   
#  OpenCADC project.                    OpenCADC.                                                                                                          
#                                                                                                                                                          
#  OpenCADC is free software:           OpenCADC est un logiciel libre ;                                                                                   
#  you can redistribute it and/or       vous pouvez le redistribuer ou le                                                                                  
#  modify it under the terms of         modifier suivant les termes de                                                                                     
#  the GNU Affero General Public        la “GNU Affero General Public                                                                                      
#  License as published by the          License” telle que publiée                                                                                         
#  Free Software Foundation,            par la Free Software Foundation                                                                                    
#  either version 3 of the              : soit la version 3 de cette                                                                                       
#  License, or (at your option)         licence, soit (à votre gré)                                                                                        
#  any later version.                   toute version ultérieure.                                                                                          
#                                                                                                                                                          
#  OpenCADC is distributed in the       OpenCADC est distribué                                                                                             
#  hope that it will be useful,         dans l’espoir qu’il vous                                                                                           
#  but WITHOUT ANY WARRANTY;            sera utile, mais SANS AUCUNE                                                                                       
#  without even the implied             GARANTIE : sans même la garantie                                                                                   
#  warranty of MERCHANTABILITY          implicite de COMMERCIALISABILITÉ                                                                                   
#  or FITNESS FOR A PARTICULAR          ni d’ADÉQUATION À UN OBJECTIF                                                                                      
#  PURPOSE.  See the GNU Affero         PARTICULIER. Consultez la Licence                                                                                  
#  General Public License for           Générale Publique GNU Affero
#  more details.                        pour plus de détails.
#                                       
#  You should have received             Vous devriez avoir reçu une
#  a copy of the GNU Affero             copie de la Licence Générale
#  General Public License along         Publique GNU Affero avec
#  with OpenCADC.  If not, see          OpenCADC ; si ce n’est
#  <http://www.gnu.org/licenses/>.      pas le cas, consultez :
#                                       <http://www.gnu.org/licenses/>.
#
#  $Revision: 4 $
#
#***********************************************************************
#

import sys
import os
import logging
import argparse

from datetime import datetime
from caom2visitor import CAOM2Visitor
from caom2visitor.commonparser import CommonParser

description =\
"""
    Visitor over a data collection in CAOM2 observation repository. The
    code provided in the plugin is for updating each visited observation.
"""


def parse_date(s):
    if s is not None:
        try:
            return datetime.strptime(s, '%Y-%m-%d')
        except ValueError as e:
            raise argparse.ArgumentTypeError(e)

"""Client script to visit a data collection in the CAOM-2 Observation Repository
   and applly changes to the data according to a custom algorithm provided in the
   plugin file.
"""


def run():
        
    parser = CommonParser(description=description,
                          formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('--plugin', required=True,
                        metavar=('<pluginClassFile>'),
                        help='Pluging class to update each observation')
    parser.add_argument('--start', metavar='<datetime start point>',
                        type=parse_date,
                        help='oldest dataset to visit (UTC %%Y-%%m-%%d format)');
    parser.add_argument('--end', metavar='<datetime end point>',
                        type=parse_date,
                        help='earliest dataset to visit (UTC %%Y-%%m-%%d format)');
    parser.add_argument('--retries', metavar='<number of retries>',
                        type=int,
                        help='number of tries with transient server errors');
    parser.add_argument("-s", "--server", metavar=('<CAOM2 service URL>'),
                      help="URL of the CAOM2 repo server")

    parser.add_argument('collection', metavar='<datacollection>', type=str,
                help='data collection in CAOM2 repo')
    parser.epilog =\
"""
Environment:
       CAOM2_VISITOR_BATCH_SIZE: the size of a get batch

Minimum plugin file format:
----
   from caom2.caom2_observation import Observation

   class ObservationUpdater:

    def update(self, observation):
        assert isinstance(observation, Observation), (
            'observation {} is not an Observation'.format(observation))
        # custom code to update the observation
----
"""
    
    args = parser.parse_args()


    if args.verbose:
        logging.basicConfig(level=logging.INFO)

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)
    
    plugin = args.plugin
    if not os.path.isfile(args.plugin):
        logging.error('Cannot find plugin file ' + plugin)
        sys.exit(-1)
    
    start = args.start
    end = args.end
    retries = args.retries
    collection = args.collection

    logging.debug("Call visitor with plugin={}, start={}, end={}, dataset={}".
           format(plugin, start, end, collection, retries))
    client = CAOM2Visitor(plugin=plugin, start=start, end=end, 
                          collection=collection, retries=retries, server=args.server)
    client.process()
    logging.debug("debug")
    
    print("DONE")

        
if __name__ == '__main__':
    run()

